---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: kargo-demo-sleep-20
  namespace: kargo-demo
spec:
  metrics:
  - name: test
    provider:
      job:
        metadata:
        spec:
          backoffLimit: 1
          template:
            spec:
              containers:
              - name: test
                image: curlimages/curl:latest
                command: [curl, "kargo-demo.kargo-demo-migrate.svc.cluster.local:3000/migrate"]
              restartPolicy: Never
