apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- patch: |-
    - op: replace
      path: /spec/ports/0/nodePort
      value: 30082
  target:
    kind: Service
    name: kargo-demo
images:
- name: docker.io/okrehel/minirepo
  newTag: 0.0.2
